name: Linting

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch: 
jobs:
  linting: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
  
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.12
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black
  
      - name: Run ruff
        run: ruff check .

      - name: Run black
        run: black --check .

      - name: Build Docker image
        run: docker build -t my-app:latest .

    # ADD THIS NEW STEP
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:latest' # Must match the tag from your build step
          format: 'table'
          exit-code: '1' # This is crucial! It fails the step if issues are found.
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH' # Only fail for Critical or High issues

  testing:
    runs-on: ubuntu-24.04

    steps:
      - name: Django testing
        run: python -m manage.py test

   # ADD THIS NEW JOB
  scan-infrastructure:
    name: Scan Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Terraform code
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/ # Point to your terraform folder
          exit_code: 1 # Fail the build on issues
      
        
      

    
    
    
    
    
